modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "simplyspeakers"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
#logoFile = "icon.png"


[[dependencies.simplyspeakers]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.215,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.simplyspeakers]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"


[[dependencies.simplyspeakers]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplyspeakers]]
modId = "openui_mc"
type = "required"
versionRange = "[${openui_version},)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.simplyspeakers]]
modId = "sable"
type = "optional"
versionRange = "[2.0.5]"
ordering = "AFTER"
side = "BOTH"


[[dependencies.simplyspeakers]]
modId = "computercraft"
type = "optional"
ordering = "AFTER"
side = "BOTH"
